spring.application.name=auth-service
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=npv0710
spring.datasource.password=123abc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

app.auth.tokenSecret=b68e52bf7d69d1785b6dbca0595205e7893561c996312dca87ed74eeb53033aa1cf581d21496546d0f8ad8995eceb391c40e070d9f0bd97f8b5d5b20a0a8a7bd
#app.auth.tokenExpiration=120000
app.auth.refreshTokenExpiration=864000000

eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
