cspring.application.name=department-service
server.port=8080
spring.config.import=optional:configserver:http://config-service:8763
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

logging.level.org.springframework.web=debug
logging.level.org.hibernate=error
logging.config=classpath:logback-spring.xml
logging.file.name=/var/log/app.log
