server.port=8081
spring.application.name=account-service
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
spring.config.import=optional:configserver:http://config-service:8763

logging.level.org.springframework.web=debug
logging.level.org.hibernate=error
logging.config=classpath:logback-spring.xml
logging.file.path=./app/logs
logging.file.name=./app/logs/app.log